# to make get request
### Get health report
GET http://localhost:3000/health

###
GET http://localhost:3000/
Authorization: Bearer <token>

###
POST  http://localhost:3000/login
Content-Type: application/json

{
    "username": "levi",
    "password": "password"
}